name = "Steampunk"
author = "OwOmay"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d235b22677a672a34602093afe5f226270a06e0c4c599262fc1853f12f6f89b"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
