name = "Steampunk"
author = "OwOmay"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d52efc8f0ae4504bdb05e527fb12b2ab695d71a60a3c73338bf0c5a646ad432f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
