name = "Steampunk"
author = "OwOmay"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d308784a3dc053c1bfbc3335e4a916a1126cd4e1fc4f920950b327690ad578"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
